In [ ]:
#Data cleaning

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('/content/titanic_dataset.csv')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.shape

(1309, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,1309.000000,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000
mean,655.000000,0.377387,2.294882,29.881138,0.498854,0.385027,33.295479
std,378.020061,0.484918,0.837836,14.413493,1.041658,0.865560,51.758668
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,328.000000,0.000000,2.000000,21.000000,0.000000,0.000000,7.895800
50%,655.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,982.000000,1.000000,3.000000,39.000000,1.000000,0.000000,31.275000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200

In [ ]:
df.loc[0,'Age']

np.float64(22.0)

In [ ]:
df.loc[0:4, ['Name','Age','Fare']]

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [ ]:
df.iloc[0:5,[3,5,9]]   # 0:5 vaneko 0n  dekhi 5 samma ko position anii 3 5 9 vankeo
# df.info garda  3 5 ra 9 position vayera

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [ ]:
# most impoprtant mamin kamm yey bata

In [ ]:
df.loc[df['Age']>60,[ 'Name', 'Age', 'Survived']]

                                                   Name   Age  Survived
33                                Wheadon, Mr. Edward H  66.0         0
54                       Ostby, Mr. Engelhart Cornelius  65.0         0
96                            Goldschmidt, Mr. George B  71.0         0
116                                Connors, Mr. Patrick  70.5         0
170                           Van der hoef, Mr. Wyckoff  61.0         0
252                           Stead, Mr. William Thomas  62.0         0
275                   Andrews, Miss. Kornelia Theodosia  63.0         1
280                                    Duane, Mr. Frank  65.0         0
326                           Nysveen, Mr. Johan Hansen  61.0         0
438                                   Fortune, Mr. Mark  64.0         0
456                           Millet, Mr. Francis Davis  65.0         0
483                              Turkula, Mrs. (Hedwig)  63.0         1
493                             Artagaveytia, Mr. Ramon  71.0         0
545                        Nicholson, Mr. Arthur Ernest  64.0         0
555                                  Wright, Mr. George  62.0         0
570                                  Harris, Mr. George  62.0         1
625                               Sutton, Mr. Frederick  61.0         0
630                Barkworth, Mr. Algernon Henry Wilson  80.0         1
672                         Mitchell, Mr. Henry Michael  70.0         0
745                        Crosby, Capt. Edward Gifford  70.0         0
829           Stone, Mrs. George Nelson (Martha Evelyn)  62.0         1
851                                 Svensson, Mr. Johan  74.0         0
893                           Myles, Mr. Thomas Francis  62.0         0
904                                Howard, Mr. Benjamin  63.0         0
972                                  Straus, Mr. Isidor  67.0         0
987   Cavendish, Mrs. Tyrell William (Julia Florence...  76.0         1
1005             Straus, Mrs. Isidor (Rosalie Ida Blun)  63.0         1
1033                         Ryerson, Mr. Arthur Larned  61.0         0
1043                                 Storey, Mr. Thomas  60.5         0
1070  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...  64.0         1
1084                                  Lingane, Mr. John  61.0         0
1127                           Warren, Mr. Frank Manley  64.0         0
1196  Crosby, Mrs. Edward Gifford (Catherine Elizabe...  64.0         1

In [ ]:
df.loc[df['Age']>60,['Name', 'Age','Survived']]

                                                   Name   Age  Survived
33                                Wheadon, Mr. Edward H  66.0         0
54                       Ostby, Mr. Engelhart Cornelius  65.0         0
96                            Goldschmidt, Mr. George B  71.0         0
116                                Connors, Mr. Patrick  70.5         0
170                           Van der hoef, Mr. Wyckoff  61.0         0
252                           Stead, Mr. William Thomas  62.0         0
275                   Andrews, Miss. Kornelia Theodosia  63.0         1
280                                    Duane, Mr. Frank  65.0         0
326                           Nysveen, Mr. Johan Hansen  61.0         0
438                                   Fortune, Mr. Mark  64.0         0
456                           Millet, Mr. Francis Davis  65.0         0
483                              Turkula, Mrs. (Hedwig)  63.0         1
493                             Artagaveytia, Mr. Ramon  71.0         0
545                        Nicholson, Mr. Arthur Ernest  64.0         0
555                                  Wright, Mr. George  62.0         0
570                                  Harris, Mr. George  62.0         1
625                               Sutton, Mr. Frederick  61.0         0
630                Barkworth, Mr. Algernon Henry Wilson  80.0         1
672                         Mitchell, Mr. Henry Michael  70.0         0
745                        Crosby, Capt. Edward Gifford  70.0         0
829           Stone, Mrs. George Nelson (Martha Evelyn)  62.0         1
851                                 Svensson, Mr. Johan  74.0         0
893                           Myles, Mr. Thomas Francis  62.0         0
904                                Howard, Mr. Benjamin  63.0         0
972                                  Straus, Mr. Isidor  67.0         0
987   Cavendish, Mrs. Tyrell William (Julia Florence...  76.0         1
1005             Straus, Mrs. Isidor (Rosalie Ida Blun)  63.0         1
1033                         Ryerson, Mr. Arthur Larned  61.0         0
1043                                 Storey, Mr. Thomas  60.5         0
1070  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...  64.0         1
1084                                  Lingane, Mr. John  61.0         0
1127                           Warren, Mr. Frank Manley  64.0         0
1196  Crosby, Mrs. Edward Gifford (Catherine Elizabe...  64.0         1

In [ ]:
df.loc[df["Age"]>60,["Survived"]].mean()  # check garxa survive ko rateeee mean la average ma

Survived    0.272727
dtype: float64

In [ ]:
df.loc[(df['Sex']=='female') & (df['Pclass']==1)].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C

In [ ]:
df.loc[(df["Sex"]=="female") & (df["Pclass"]==1)].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C

In [ ]:
df.loc[(df["Sex"]=="male") & (df["Pclass"]==2)].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0,D56,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5,NaN,S
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.0,0,0,C.A. 33111,10.5,NaN,S

In [ ]:
# most important tyo sab herisakesi aba hamla value update garnu p

In [ ]:
df.loc[df['Age']<16, 'Group']='Child'
df.loc[df['Age']>=16,'Group'] = 'Adult'

In [ ]:
df[['Name', 'Age' , 'Group']].head(10)

                                                Name   Age  Group
0                            Braund, Mr. Owen Harris  22.0  Adult
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  Adult
2                             Heikkinen, Miss. Laina  26.0  Adult
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  Adult
4                           Allen, Mr. William Henry  35.0  Adult
5                                   Moran, Mr. James   NaN    NaN
6                            McCarthy, Mr. Timothy J  54.0  Adult
7                     Palsson, Master. Gosta Leonard   2.0  Child
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  Adult
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0  Child

In [ ]:
#group garisakesi hamila missing value herne

In [ ]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S,Adult

In [ ]:
# missing value find garni suruma

In [ ]:
df.isnull() .sum() # missing value sum garera herni herni

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
Group           263
dtype: int64

In [ ]:
(df.isnull().mean() * 100).round(1) # percentage ma lani nikalna sajilo hunxa vanera
# cabin delete garna parni hunxa

PassengerId     0.0
Survived        0.0
Pclass          0.0
Name            0.0
Sex             0.0
Age            20.1
SibSp           0.0
Parch           0.0
Ticket          0.0
Fare            0.1
Cabin          77.5
Embarked        0.2
Group          20.1
dtype: float64

In [ ]:
df.loc[df["Age"].isnull(),["Name","Age", "Pclass"]]
#age ma null vako hereko tesko name p class k raixa vanera hereko

                                 Name  Age  Pclass
5                    Moran, Mr. James  NaN       3
17       Williams, Mr. Charles Eugene  NaN       2
19            Masselmani, Mrs. Fatima  NaN       3
26            Emir, Mr. Farred Chehab  NaN       3
28      O'Dwyer, Miss. Ellen "Nellie"  NaN       3
...                               ...  ...     ...
1299  Riordan, Miss. Johanna Hannah""  NaN       3
1301           Naughton, Miss. Hannah  NaN       3
1304               Spector, Mr. Woolf  NaN       3
1307              Ware, Mr. Frederick  NaN       3
1308         Peter, Master. Michael J  NaN       3

[263 rows x 3 columns]

In [ ]:
df=df.drop( columns=['Cabin'])

In [ ]:
df.info() # 12 0ta bata 11 ota  column baniyo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Embarked     1307 non-null   object
 11  Group        1046 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'Group'],
      dtype='object')

In [ ]:
df["Embarked"].mode()[0]

'S'

In [ ]:
df['Embarked']= df['Embarked'].fillna(df['Embarked'].mode()[0])

In [ ]:
df['Embarked'].mode()[0]  # embarked lai fill garna mode 0 garera herni ami fill garni

'S'

In [ ]:
df['Embarked']= df['Embarked'].fillna(df['Embarked'].mode()[0])

In [ ]:
df.loc[df['Embarked'].isna(), 'Embarked'] = df['Embarked'].mode()[0]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Embarked     1309 non-null   object
 11  Group        1046 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

In [ ]:
median_age=df['Age'].median() # median age nikalelo ani balla  fill garna
print(  'median age :', median_age)

median age : 28.0

In [ ]:
df.loc[df['Age'].isna(), 'Age'] = median_age

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Embarked         0
Group          263
dtype: int64

In [ ]:
# aba age fill up ni vaisakesi feri mathi ko condition run garne

In [ ]:
df.loc[df["Age"]<16, 'Group']= 'Child'
df.loc[df["Age"]>=16, 'Group']= 'Adult'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1309 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Embarked     1309 non-null   object
 11  Group        1309 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

In [ ]:
 #duplicate huna sakxa teslai hatauna paryo

In [ ]:
#duplicate data add garxam just for an example bujna ko lagiii

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df=pd.concat([df, df.iloc[0:3]], ignore_index=True)

In [ ]:
df.duplicated().sum()

np.int64(3)

In [ ]:
print('Rows  now:', len(df))
print('Duplicate now:', df.duplicated().sum())

Rows  now: 1312
Duplicate now: 3

In [ ]:
df= df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#to  fix datatypes
df['Survived']= df['Survived'].astype(int)
df['Sex']= df['Sex'].astype('category')
df['Embarked']= df['Embarked']. astype('category')

df.dtypes

/tmp/ipykernel_642/1685844635.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Survived']= df['Survived'].astype(int)
/tmp/ipykernel_642/1685844635.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex']= df['Sex'].astype('category')
/tmp/ipykernel_642/1685844635.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked']= df['Embarked']. astype('category')

PassengerId       int64
Survived          int64
Pclass            int64
Name             object
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Embarked       category
Group            object
dtype: object

In [ ]:
df.shape

(1309, 12)

In [ ]:
# fare bata  fill garna baki rahyo last
df['Fare'].describe()

count    1308.000000
mean       33.295479
std        51.758668
min         0.000000
25%         7.895800
50%        14.454200
75%        31.275000
max       512.329200
Name: Fare, dtype: float64

In [ ]:
df.loc[df['Fare']>300,['Name', 'Pclass','Fare']]

                                                   Name  Pclass      Fare
258                                    Ward, Miss. Anna       1  512.3292
679                  Cardeza, Mr. Thomas Drake Martinez       1  512.3292
737                              Lesurer, Mr. Gustave J       1  512.3292
1234  Cardeza, Mrs. James Warburton Martinez (Charlo...       1  512.3292

In [ ]:
df['Survived'] = df['Survived'].astype(int)
df['Sex'] = df['Sex'].astype('category')
df['Embarked'] = df['Embarked'].astype('category')

df.dtypes

/tmp/ipykernel_642/4043080556.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Survived'] = df['Survived'].astype(int)
/tmp/ipykernel_642/4043080556.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = df['Sex'].astype('category')
/tmp/ipykernel_642/4043080556.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked'] = df['Embarked'].astype('category')

PassengerId       int64
Survived          int64
Pclass            int64
Name             object
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Embarked       category
Group            object
dtype: object

In [ ]:
q1 = df['Fare'].quantile(0.25)
q3 = df['Fare'].quantile(0.75)

Iqr = q3 - q1

upper = q3 + 1.5 * Iqr

print('q1:', q1, 'q3:', q3, 'upper limit:', round(upper, 2))
print('outliers:', (df['Fare'] > upper).sum())

q1: 7.8958 q3: 31.275 upper limit: 66.34
outliers: 171

In [ ]:
df.loc[df['Fare'] > upper, 'Fare'] = upper
df['Fare'].describe()

count    1308.000000
mean       24.287208
std        20.795666
min         0.000000
25%         7.895800
50%        14.454200
75%        31.275000
max        66.343800
Name: Fare, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   category
 5   Age          1309 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Embarked     1309 non-null   category
 11  Group        1309 non-null   object
dtypes: category(2), float64(2), int64(5), object(3)
memory usage: 115.3+ KB

In [ ]:
print('Missing values:', df.isnull().sum().sum())
print('Duplicates:', df.duplicated().sum())
print('Shape:', df.shape)

Missing values: 1
Duplicates: 0
Shape: (1309, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   category
 5   Age          1309 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Embarked     1309 non-null   category
 11  Group        1309 non-null   object
dtypes: category(2), float64(2), int64(5), object(3)
memory usage: 115.3+ KB

In [ ]:
df.to_csv('titanic_clean.csv', index=False)
print('saved titanic_clean.csv')

saved titanic_clean.csv